### ISSUE TITLE
10.0.7 Checklist/Testplan

### ISSUE THREAD

**Issue by voroyam** [owncloud/appliance#11]
- [x] Upgrade to new version from old version
- [x] Log in ownCloud via IP and HTTP
- [x] * https & IP
- [x] * https & domain name
- [x] Upload a file
- [x] Overwrite a file by uploading a new version
- [x] Enable OnlyOffice in ownCloud
- [x] Install & Configure the OnlyOffice App
- [x] Create new document in ownCloud
- [x] Enable Collabora in ownCloud
- [x] Install & Configure the Collabora App
- [x] Rename a file
- [x] Create a folder
- [x] Move a file inside a folder
- [x] Move a folder inside another
- [x] Remove a file
- [x] Delete a folder
- [x] Create a new local user
- [x] Create new user and group in UCS
- [x] Sync LDAP users in ownCloud
- [x] Check the users tab for the LDAP users
- [x] Share a file by link
- [x] Share a file with a local group
- [x] Login as local user in that group and check
- [x] Share a file with a LDAP group
- [x] Login as LDAP user in that group and check
- [x] Activate the enterprise trial
-------------------
added tests from @CaptionF feedback

- [x] WND: mount storage
- [x] Email-Configuration
- [x] Guest app: Invite guest to share
-------------------
- [x] All tests completed
