### ISSUE TITLE
10.1.1 Release Checklist

### ISSUE THREAD

**Issue by voroyam** [owncloud/appliance#49]
- Database:

- [x] Works on new install
- [ ] Works on update from earlier versions (10.0.4)

- App Settings / Variable Setting
- [x] Is OWNCLOUD_DOMAIN set correctly?
- [x] Does the enterprise+Market API Key works via app settings?
